fix: escape keystore_info params passed to bundletool
Hi, I tried to use your action but I am currently facing some problems, I keep getting the following error

```sh
[20:59:20]: Bundletool could not extract universal apk from aab at /home/runner/work/***/***/android/app/build/outputs/bundle/release/app-release.aab. 
Error message
 sh: 1: stGAXs: not found
[BT:0.11.0] Error: Incorrect keystore password.
com.android.tools.build.bundletool.model.exceptions.CommandExecutionException: Incorrect keystore password.
	at com.android.tools.build.bundletool.model.SigningConfiguration.extractFromKeystore(SigningConfiguration.java:116)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.fromFlags(BuildApksCommand.java:457)
	at com.android.tools.build.bundletool.commands.BuildApksCommand.fromFlags(BuildApksCommand.java:417)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:74)
	at com.android.tools.build.bundletool.BundleToolMain.main(BundleToolMain.java:46)
```

After a bit of debugging it looks like the parameters passed down to bundle tools are not escaped, with this simple fix we should now be able to use special chars as a password.

Let me know if something is missing in this pr, thanks for this nice plugin!